name = "grain"
# grammar = "grain"
path_suffixes = ["gr"]
line_comments = ["// "]
block_comments = ["/*", "*/"] # TODO: Should we add doc comments here
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
    "string",
  ] },
  { start = "'", end = "'", close = true, newline = false, not_in = [
    "string",
    "comment",
  ] },
]
tab_size = 2
