id = "grain"
name = "Grain"
version = "0.0.1"
schema_version = 1
authors = ["spotandjake", "Kara-Zor-El"]
description = "Grain support for Zed"
repository = "https://github.com/spotandjake/zed-grain"

[grammars.grain]
repository = "https://github.com/Kara-Zor-El/tree-sitter-grain"
commit = "0c06f8e0ece0cddac70710a561fddabd5ebf2ecb"

[language_servers.grain]
name = "Grain Language Server"
language = "grain"
