id = "grain"
name = "Grain"
version = "0.0.1"
schema_version = 1
authors = ["spotandjake"]
description = "Grain support for Zed"
repository = "https://github.com/spotandjake/zed-grain"

[grammars.grain]
repository = "https://github.com/Kara-Zor-El/tree-sitter-grain"
commit = "c0d72c602faf41a65ad14284fe00736c392dfb07"

[language_servers.grain]
name = "Grain Language Server"
language = "grain"
